# Generated by Django 2.2.4 on 2019-08-27 12:41

from django.db import migrations
from products.models import Category


def create_default_category(apps, schema_editor):
    Category.objects.create(
        name='Vegetables'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category'),
    ]

    operations = [
        migrations.RunPython(create_default_category)
    ]
