# Generated by Django 2.2.4 on 2019-08-27 12:47

from django.db import migrations, models
import django.db.models.deletion
from products.models import Category

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190827_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                default=Category.objects.first().id, 
                on_delete=django.db.models.deletion.CASCADE, to='products.Category'
            ),
            preserve_default=False,
        ),
    ]
